code changed

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -1,16 +1,48 @@
-name: Cron jobs 
- 
-on:
-  schedule:
-    - cron: "* *  * * *" 
+# Name of the worflow
+name: hello worflow
+
+
+on: 
+  workflow_dispatch: 
+# Trigger the workflow Every day at midnight UTC
+  # schedule:
+  #   - cron: "0 0 * * *"  # Every day at midnight UTC
+
+# Define the jobs that will run in this workflow
 jobs:
   greet:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Check Repository
-        uses: actions/checkout@v4
 
-      - name: Print Greeting
-        run: echo "hello from github action"
-      - name: Print the current data and time 
-        run: date     
+    # specify the runner environment
+    runs-on: ubuntu-latest
+    
+    # Steps represents of tasks executed as a part of the job
+    steps:
+      # Step 1: Checkout the repository 
+      - name: Check repository
+        uses: actions/checkout@v4
+        
+      # Step 2: Print greeting
+      - name: Print greeting
+        run: echo "Hello from GitHub Actions!"
+
+      # Step 3: Print the current date and time
+      - name: Print the current date and time
+        run: date
+
+      # Step 4: Print branch name
+      - name: Print branch name
+        run: |
+          echo "Triggered by branch: ${{ github.ref_name }}"
+
+      # Step 5 List repo file
+      - name: List repo files
+        run: ls -la
+
+      # Step 6 Print runner operating system
+      - name: Print runner OS
+        run: |
+          echo "Runner OS: ${{ runner.os}}"
+
+      # Step 6 Intentionally fail    
+      # - name: Break the workflow on purpose
+      #   run: exit 1  
